# Generated by Django 4.2.21 on 2025-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='about/images')),
                ('content', models.TextField()),
            ],
        ),
    ]
