# Generated by Django 4.2.21 on 2025-06-03 21:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
