# Generated by Django 4.2.21 on 2025-07-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('cottage_id', models.CharField(default='Pen Y Graig', max_length=20, primary_key=True, serialize=False)),
                ('featured_image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='cottages/featured')),
                ('description', models.CharField(blank=True, default='Untitled Cottage', max_length=400, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='cottages/hero')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CottageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='cottages/images')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('import_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cottages.cottage')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('featured_image', models.ImageField(blank=True, default='placeholder', null=True, upload_to='cottages/featured')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body', models.TextField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
                'unique_together': {('guest', 'cottage', 'created_on')},
            },
        ),
    ]
