# Generated by Django 4.2.21 on 2025-06-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cottage',
            field=models.ForeignKey(default='Pen Y Graig', on_delete=django.db.models.deletion.CASCADE, to='cottages.cottage'),
            preserve_default=False,
        ),
    ]
