# Generated by Django 4.2.21 on 2025-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='cottage_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
