# Generated by Django 4.2.21 on 2025-06-03 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cottages', '0003_review_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Untitled Review', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('guest', 'cottage')},
        ),
    ]
