# Generated by Django 4.2.21 on 2025-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0004_review_slug_review_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='description',
            field=models.CharField(blank=True, default='Untitled Cottage', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
