# Generated by Django 4.2.21 on 2025-06-06 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cottages', '0007_alter_review_options_remove_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cottage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(default='Please write your review here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cottages.cottage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('guest', 'cottage', 'created_on')},
        ),
    ]
