# Generated by Django 4.2.21 on 2025-06-06 22:23

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Cottage = apps.get_model('cottages', 'Cottage')
    for cottage in Cottage.objects.all():
        cottage.slug = slugify(cottage.name or f'cottage-{cottage.id}')
        cottage.save()

class Migration(migrations.Migration):
    dependencies = [
        ('cottages', '0008_alter_review_unique_together_cottage_slug_and_more'),
    ]
    operations = [
        migrations.RunPython(generate_slugs),
    ]
