# Generated by Django 4.2.21 on 2025-06-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0009_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
