# Generated by Django 4.2.21 on 2025-06-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0010_alter_review_body_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cottages/'),
        ),
    ]
