# Generated by Django 4.2.21 on 2025-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0012_remove_cottage_image_cottageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottageimage',
            name='import_batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
