# Generated by Django 4.2.21 on 2025-06-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0013_cottageimage_import_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='description',
            field=models.CharField(blank=True, default='Untitled Cottage', max_length=400, null=True),
        ),
    ]
