# Generated by Django 4.2.21 on 2025-06-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottages', '0014_alter_cottage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
